version: "3.9"
services:
  ffmpeg:
    image: local/ffmpeg
    build: docker_ffmpeg_image/.
    volumes:
      - /dev/dri:/dev/dri
      - ./hls:/root/hls
    network_mode: "host"
    environment: 
      - SRC_UDP=239.9.123.3:5000
      - ROOT_URL=http://10.32.8.11:12080
    working_dir: /root
    command: /root/hls/ffmpeg_stream.sh
  web:
    image: httpd:latest
    volumes: 
      - ./hls/web:/usr/local/apache2/htdocs/
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "12080:80"
